# Generated by Django 6.0 on 2026-01-05 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('spice_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Hot', 'Hot')], max_length=10)),
                ('salt_level', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('Extra', 'Extra')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
