# Generated by Django 6.0 on 2026-01-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('default_spice', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Hot', 'Hot')], default='Medium', max_length=10)),
                ('default_salt', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('Extra', 'Extra')], default='Normal', max_length=10)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
