# Generated by Django 6.0 on 2026-01-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(blank=True, choices=[('appetizer', 'Appetizer'), ('main', 'Main Dish'), ('dessert', 'Dessert'), ('drink', 'Drink')], max_length=50, null=True),
        ),
    ]
