# Generated by Django 6.0 on 2026-01-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_menuitem_image_alter_teammember_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
